server:
  port: 8087

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: JWT-AUTH-SERVER
          uri: lb://JWT-AUTH-SERVER
          predicates:
            - Path=/api/auth/**, /api/test/**
        #          filters:
        #            - AuthenticationFilter

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotels/**
          filters:
            - AuthenticationFilter

        - id: GUEST-SERVICE
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/api/guests/**
        #          filters:
        #           - AuthenticationFilter

        - id: REVIEW-SERVICE
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/reviews/**
        #          filters:
        #            - AuthenticationFilter

        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**
        #          filters:
        #            - AuthenticationFilter



      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    web-application-type: reactive

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


